Repository Plant-for-the-Planet-org/treecounter-app, pull requests merged in 2019-12, with the labels that each got.

#1713 Added invoice_numer : ttc-donationId to paypal, to track payment source
  app/components/Payment/AppPayments.js
  app/components/Payment/Gateways/Paypal.js
  app/components/Payment/PaymentSelector.js
  app/components/Payment/PaymentSelector.native.js
Labels: new react-native

#1714 Commenting offline payment fixes the issue as we dont use offline any…
  app/components/Payment/PaymentSelector.js
Labels: new react-native

#1693 Donation v1.2: release candidate
  app/assets/images/icons/right-arrow-button.png
  app/assets/index.js
  app/components/Common/Button/FullHeightButton.native.js
  app/components/Competition/CompetitionParticipant.native.js
  app/components/Navigators/AppDrawerNavigator.js
  app/components/PlantProjects/PlantProjectFull.native.js
  app/components/PlantProjects/PlantProjectSnippet.native.js
  app/components/PlantProjects/PlantedProgressbar.native.js
  app/components/PublicTreeCounter/PublicTreecounter.native.js
  app/styles/common/button.native.js
  app/styles/selectplantproject/selectplantproject-full.native.js
  app/styles/selectplantproject/selectplantproject-snippet.native.js
Labels: new react-native

#1723 Reviews fix, images new look
  app/actions/reviews.js
  app/components/Common/Forms/AddImage.native.js
  app/components/Reviews/AddReview/AddRatingSection.js
  app/components/Reviews/AddReview/AddReview.js
  app/components/Reviews/SingleReview.js
  app/styles/review.native.js
Labels: new react-native

#1696 Feature/translation fixes
  app/components/Competition/index.native.js
  app/components/EditUserProfile/PlantProjectTemplate.js
  app/components/Navigators/AppDrawerNavigator.js
  app/components/Pledge/eventDetails.js
  app/components/Pledge/index.js
  app/components/Pledge/modals.js
  app/components/PledgeEvents/MakePledgeForm.native.js
  app/components/PledgeEvents/PledgeEvents.native.js
  app/components/PledgeEvents/PledgeTabView.native.js
  app/components/PledgeEvents/UnfulfilledPledgeEvent.native.js
  app/components/PledgeEvents/UpdatePledgeEvent.native.js
  app/components/TreecounterGraphics/FeaturedProjectScroll/Events.native.js
  app/components/TreecounterGraphics/FeaturedProjectScroll/UnfulfilledEvents.native.js
  app/locales/de/index.js
  app/locales/de/pledgelabels.json
  app/locales/en/pledgelabels.json
  app/locales/es/index.js
Labels: new react-native

#1740 temporary replace license component with link to GitHub dependencies
  app/components/AboutUs/index.native.js
Labels: bug

#1706 adding support for jest / updated babel
  .babelrc
  .gitignore
  __mocks__/@react-native-community/async-storage/index.js
  __mocks__/@react-native-community/geolocation.js
  __mocks__/react-native-i18n.js
  __mocks__/react-native-permissions.ts
  __tests__/App-test.js
  babel.config.js
  jest.config.js
  package.json
  web/.babelrc
  web/config/webpack.common.config.js
  web/config/webpack.dev.config.js
  web/config/webpack.prod.config.js
  web/config/webpack.prod_server.config.js
  web/config/webpack.server.config.js
Labels: tooling

#1754 fix undefined refreshToken function calls
  app/containers/Authentication/LoginContainer.js
  app/containers/Authentication/SignUpContainer.js
Labels: bug

#1757 do not use Linking.canOpenURL any more, catch error instead
  app/components/AboutUs/index.native.js
  app/components/DonateTrees/index.native.js
  app/components/PlantProjects/PlantProjectDetails.native.js
  app/components/PublicTreeCounter/PublicTreecounter.native.js
  app/components/UserHome/index.native.js
Labels: bug

#1758 if refs don't work, use parameter to get value of email form
  app/components/EditUserProfile/index.native.js
Labels: bug
