Repository Plant-for-the-Planet-org/treecounter-app, pull requests merged in 2019-11, with the labels that each got.

#1597 Fixed donation issue support
  app/components/DonateTrees/index.js
Labels: P1

#1581 Feature/npm update
  package.json
Labels: tooling

#1629 Do not cut donation amount for a large number of trees
  app/components/Currency/TreeCountSelector.js
  web/stylesheet/donateTrees/_donate_trees.scss
Labels: bug

#1622 Fix currency issue on production
  app/components/DonateTrees/index.js
  app/containers/DonateTrees/index.js
  app/utils/utils.js
Labels: bug

#1624 Validation fixed for register tree issue #1577
  app/components/RegisterTrees/index.js
  app/containers/RegisterTrees/index.js
Labels: Web, bug, client

#1642 Feature/pledge event fix api call loop
  app/actions/pledgeEventsAction.js
  app/components/Pledge/index.js
  app/components/PledgeEvents/PledgeEvents.native.js
  app/components/TreecounterGraphics/Trillion.native.js
Labels: bug

#1667 Fix adding too much user profile information into forms and sending to API
  app/components/DonateTrees/index.js
Labels: bug
