Repository Plant-for-the-Planet-org/treecounter-app, pull requests merged in 2020-05, with the labels that each got.

#2250 allow challenge end date to be chosen in the future
  app/components/Competition/Tabs/formComponents.native.js
  app/components/Competition/editFormComponents.native.js
  app/helpers/utils.js
Labels: bug

#2267 fixed user contribution links for web client
  app/components/Common/Text/TextSpan.js
  app/components/UserContributions/ContributionCard.js
Labels: bug

#2268 fixed wrong route in web client for accepting a challenge
  app/components/App/TreeCounter.js
  app/components/Challenge/RedirectedPrivateAcceptEmail.js
  app/containers/Challenge/RedirectedPrivateAcceptEmail.js
Labels: bug

#2074 added support for Spanish language
  app/actions/getLocale.js
  app/actions/getLocale.native.js
  app/assets/images/es/apple-store-badge.png
  app/assets/images/es/google-play-badge.png
  app/assets/images/spain.png
  app/assets/index.js
  app/components/Menu/index.js
  app/locales/cs/leaderboradlabels.json
  app/locales/de/index.js
  app/locales/de/leaderboradlabels.json
  app/locales/en/index.js
  app/locales/en/leaderboradlabels.json
  app/locales/es/index.js
  app/locales/es/leaderboradlabels.json
  app/locales/fr/leaderboradlabels.json
  app/locales/i18n.js
  app/locales/i18n.native.js
  app/locales/it/leaderboradlabels.json
  app/locales/pt-BR/leaderboradlabels.json
  app/locales/pt/leaderboradlabels.json
  ios/TreecounterApp.xcodeproj/project.pbxproj
Labels: translation

#2222 retrieve WebMapIds from config API call and remove from env
  .env.deploy
  .env.develop.sample
  .env.fixtures.sample
  .env.production.sample
  .env.staging.sample
  app/actions/apiRouting.js
  app/actions/fetchConfig.js
  app/components/Map/ArcGISContributionCaptureMap.js
  app/components/Map/ArcGISContributionsMap.js
  app/components/PublicTreeCounter/UserFootprint.js
  app/config/index.js
  app/config/index.native.js
  app/containers/Leaderboard/index.js
  app/reducers/configReducer.js
  app/selectors/index.js
Labels: architecture

#2270 refactored refresh_token functionality
  app/stores/localStorage.native.js
  app/utils/user.js
Labels: bug

#2269 Image not visible when update tree and image not update
  app/actions/EditMyTree.js
  app/components/EditUserContribution/index.native.js
  app/components/PlantProjects/PlantProjectImageCarousel.native.js
  app/components/RegisterTrees/formComponents.native.js
  app/components/RegisterTrees/index.js
  app/components/Templates/FilePickerTemplate.js
  app/containers/EditUserContribution/index.js
  app/helpers/utils.js
  app/server/formSchemas/registerTrees.js
  app/server/parsedSchemas/registerTrees.js
  app/styles/register_trees.native.js
Labels: bug

#2323 Feature/edit profile loader
  app/actions/updateUserProfile.js
  app/components/Common/Button/PrimaryButton.native.js
  app/components/EditUserProfile/index.native.js
  app/containers/EditUserProfile/index.js
Labels: bug

#2332 Fixed currency set on currency select modal
  .gitignore
  app/components/Common/CurrencySelectorList.native.js
  app/components/Currency/GlobalCurrencySelector.js
Labels: bug

#2331 added basic support for Portuguese (brazil) languages
  app/actions/getLocale.js
  app/actions/getLocale.native.js
  app/assets/images/flags/brazil.png
  app/assets/images/flags/germany.png
  app/assets/images/flags/portugal.png
  app/assets/images/flags/spain.png
  app/assets/images/pt-BR/apple-store-badge.png
  app/assets/images/pt-BR/google-play-badge.png
  app/assets/images/pt/apple-store-badge.png
  app/assets/images/pt/google-play-badge.png
  app/assets/index.js
  app/components/Menu/index.js
  app/locales/Intl.native.js
  app/locales/i18n.js
  app/locales/i18n.native.js
  app/locales/pt-BR/index.js
  app/locales/pt/index.js
  ios/TreecounterApp.xcodeproj/project.pbxproj
  ios/TreecounterApp/de.lproj/LaunchScreen.xib
  ios/TreecounterApp/en.lproj/LaunchScreen.strings
  ios/TreecounterApp/en.lproj/LaunchScreen.xib
  ios/TreecounterApp/es.lproj/LaunchScreen.strings
  ios/TreecounterApp/es.lproj/LaunchScreen.xib
  ios/TreecounterApp/pt-BR.lproj/LaunchScreen.strings
  ios/TreecounterApp/pt-BR.lproj/LaunchScreen.xib
  ios/TreecounterApp/pt.lproj/LaunchScreen.strings
  ios/TreecounterApp/pt.lproj/LaunchScreen.xib
  ios/pt.lproj/InfoPlist.strings
Labels: translation

#2361 Fixing update to treecounter after redeem
  app/actions/redemptionAction.js
  app/containers/RedemptionContainer/index.js
  app/containers/RedemptionContainer/index.native.js
Labels: bug
