Repository Plant-for-the-Planet-org/treecounter-app, pull requests merged in 2020-02, with the labels that each got.

#1888 added sync and async getLocale functions for native apps
  app/actions/apiRouting.js
  app/actions/getLocale.native.js
Labels: bug

#1886 changed bottom navi to vertically align text and thin font icons
  app/containers/Menu/StaticTabbar.tsx
Labels: bug

#1897 fix competition and gift user button issue
  app/components/Competition/Tabs/formComponents.native.js
  app/components/GiftTrees/Tabs/GiftUser.native.js
Labels: bug

#1920 upgrade react-tooltip
  app/components/Header/UserDetails.js
  package.json
  web/widgets/Treecounter/app/components/App.js
  web/widgets/progressbar/app/components/App.js
Labels: tooling

#1898 Feature/adjust map providers logo
  app/components/Map/NativeMapView.native.js
  app/components/UserContributions/userContribution.native.js
  app/components/UserHome/index.native.js
Labels: bug

#1975 Feature/private label leaderboard
  app/components/LeaderboardRefresh/Companies/CompaniesLeaderBoard.js
  app/components/LeaderboardRefresh/Countries/CountriesLeaderBoard.js
  app/components/LeaderboardRefresh/Countries/CountryDetails.js
  app/components/LeaderboardRefresh/Individuals/IndividualsLeaderBoard.js
  app/components/LeaderboardRefresh/Schools/SchoolsLeaderBoard.js
  app/components/LeaderboardRefresh/TPOs/tpoLeaderBoard.js
  app/locales/en/leaderBoardRefresh/countryDetails.json
  app/styles/LeaderboardRefresh/Countries/CountryLeaderboardStyle.js
Labels: old-config version

#1983 fixed eslint errors in develop branch
  app/components/PlantProjects/PlantProjectSnippet.native.js
  app/components/PlantProjects/PlantProjectSnippetDetails.native.js
  app/components/PublicTreeCounter/PublicTreecounter.native.js
  app/components/TreecounterGraphics/Trillion.native.js
Labels: bug

#1988 Fix date chooser input problem in competitions
  app/components/Competition/Tabs/formComponents.native.js
  app/components/Competition/editFormComponents.native.js
Labels: bug

#1997 Fix donation project fetch nan issue
  app/containers/DonateTrees/index.js
Labels: bug

#2002 solved TypeError bug on navigating to home from regiser tree
  app/components/RegisterTrees/RegisterTreeTab.native.js
  app/components/RegisterTrees/formComponents.native.js
Labels: bug

#2003 Competition Details all enrollments error
  app/components/Competition/CompetitionFull.native.js
  app/containers/TargetContainer/index.js
Labels: bug

#2005 Feature/fix console red warnings
  app/components/Authentication/Login/index.native.js
  app/components/Common/Checkbox/index.native.js
  app/components/EditUserContribution/index.native.js
  app/components/Map/NativeMapView.native.js
  app/components/PlantProjects/PlantedProgressbar.js
  app/components/RegisterTrees/RegisterTreeTab.native.js
  app/components/RegisterTrees/formComponents.native.js
  app/components/SelectPlantProject/index.js
  app/components/UserContributions/userContribution.native.js
Labels: bug

#2009 Fixed loading missing project details for donation container
  app/containers/DonateTrees/index.js
Labels: bug
