Repository Plant-for-the-Planet-org/treecounter-app, pull requests merged in 2020-04, with the labels that each got.

#2164 Fixed broken multiple trees registration
  app/components/RegisterTrees/index.js
  app/components/UserContributions/ContributionCard.js
  app/locales/en/registerTreeslabels.json
Labels: bug

#2199 fix Android deep linking
  app/components/DonateTrees/index.native.js
  app/components/Menu/index.native.js
Labels: bug

#2226 fix tpo registration tree crash issue when select plant project from …
  app/components/Common/ContentLoader.native.js
  app/components/EditUserContribution/index.js
  app/components/EditUserContribution/index.native.js
  app/components/Map/NativeMapView.native.js
  app/components/RegisterTrees/RegisterTreeTab.native.js
  app/components/RegisterTrees/formComponents.native.js
  app/components/RegisterTrees/index.native.js
  app/components/UserContributions/ContributionDetails/index.native.js
  app/containers/EditUserContribution/index.js
  app/helpers/utils.js
  app/server/formSchemas/registerTrees.js
Labels: backend, bug

#2241 Use live data from api call in featured list: web
  .gitignore
  app/components/SelectPlantProject/index.js
  app/containers/SelectPlantProject/index.js
Labels: bug

#2260 added unit specification to tree registration labels
  app/components/RegisterTrees/formComponents.native.js
  app/locales/de/registerTreeslabels.json
  app/locales/en/registerTreeslabels.json
  app/locales/es/registerTreeslabels.json
Labels: bug

#2244 Feature/GitHub actions
  .github/workflows/macos_build_android.yml.disabled
  .github/workflows/macos_build_ios.yml
  .github/workflows/ubuntu_build_android.yml
  README.md
  android/app/build.gradle
  release/31f528b5-e436-47ab-b159-9d59e9abb155.mobileprovision.gpg
  release/36898aad-d25b-4d4a-bc71-05faedd579f1.mobileprovision.gpg
  release/Adhoc-Store.plist
  release/App-Store.plist
  release/AppStoreCertificates.p12.gpg
  release/Develop-Store.plist
  release/d7eac000-9967-4d71-b570-0262a5c3fb21.mobileprovision.gpg
  release/prepare_macos_ios_signing.sh
  release/upload-native-source-maps.sh
Labels: tooling

#2206 use dedicated api_url for API calls
  .circleci/config.yml
Labels: architecture
