Repository Plant-for-the-Planet-org/treecounter-app, pull requests merged in 2020-03, with the labels that each got.

#2014 separate API url from website
  .env.deploy
  .env.develop.sample
  .env.production.sample
  .env.staging.sample
  app/actions/apiRouting.js
  app/components/GiftTrees/index.js
  app/components/Header/SearchAutosuggest.js
  app/config/index.js
  app/config/index.native.js
  app/containers/DonateTrees/index.js
  app/helpers/mediaPath.js
  app/helpers/utils.js
  app/utils/api.js
Labels: tooling

#1991 single tree contribution data and link issue
  app/components/Competition/CompetitionFull.native.js
  app/components/UserContributions/ContributionDetails/index.native.js
  app/components/UserContributions/userContribution.native.js
  app/containers/SelectedPlantProject/index.js
  app/containers/UserContributionsDetails/index.js
  app/locales/en/userContributionslabels.json
  app/styles/newUserContributions/userContributions.js
Labels: 1.3.2, bug

#1969 leaderboard filtring and sorting issue fixed
  app/containers/Leaderboard/index.js
Labels: backend, bug

#2016 Features/npm update dependence
  __tests__/App-test.js
  android/settings.gradle
  app/components/Authentication/Login/index.js
  app/components/Authentication/SignUp/SignUp.js
  app/helpers/reduxHelpers.native.js
  index.native.js
  ios/TreecounterApp.xcodeproj/project.pbxproj
  package.json
Labels: tooling

#2047 Fixed No internet issue for iOS
  app/containers/Menu/NewBottomNavigator.js
  app/locales/en/commonlabels.json
Labels: bug

#2050 Pledge event: pledge event not found clicking on unfulfilled pledge
  app/components/TreecounterGraphics/Trillion.native.js
Labels: bug

#2046 Redeem Navigation Changed
  app/components/Redemption/app/AddTrees.native.js
  app/styles/redeem.native.js
Labels: bug

#2070 fix crash from uuid in native apps
  app/components/Authentication/Login/index.js
  app/components/Authentication/SignUp/SignUp.js
  app/utils/api.js
  app/utils/uuid.js
  app/utils/uuid.native.js
Labels: bug
